// frontend/apps/mbl-react-mantine/src/providers/LocaleProvider.tsx
import React, { createContext, useContext, useState } from "react";
import {
  detectBrowserLocale,
  type SupportedLocale,
} from "../utils/locale-detector";

interface LocaleContextType {
  currentLocale: SupportedLocale;
  setLocale: (locale: SupportedLocale) => void;
}

const LocaleContext = createContext<LocaleContextType | undefined>(undefined);

export const useLocale = () => {
  const context = useContext(LocaleContext);
  if (!context) {
    throw new Error("useLocale must be used within a LocaleProvider");
  }
  return context;
};

interface LocaleProviderProps {
  children: React.ReactNode;
}

export const LocaleProvider: React.FC<LocaleProviderProps> = ({ children }) => {
  const [currentLocale, setCurrentLocale] = useState<SupportedLocale>(() => {
    // 从 localStorage 读取保存的语言环境
    const savedLocale = localStorage.getItem("app-locale") as SupportedLocale;
    const validLocales: SupportedLocale[] = ["zh-CN", "en-US"];

    // 如果有保存的语言设置，使用保存的设置
    if (savedLocale && validLocales.includes(savedLocale)) {
      return savedLocale;
    }

    // 否则自动检测浏览器语言
    return detectBrowserLocale();
  });

  const setLocale = (locale: SupportedLocale) => {
    setCurrentLocale(locale);
    localStorage.setItem("app-locale", locale);
  };

  return (
    <LocaleContext.Provider value={{ currentLocale, setLocale }}>
      {children}
    </LocaleContext.Provider>
  );
};

// frontend/apps/mbl-vue-element-plus/src/providers/LocaleProvider.vue
<template>
  <slot />
</template>

<script setup lang="ts">
import { ref, provide, onMounted } from 'vue'
import { detectBrowserLocale, type SupportedLocale } from '../utils/locale-detector'

// 语言状态
const currentLocale = ref<SupportedLocale>('zh-CN')

// 语言切换方法
const setLocale = (locale: SupportedLocale) => {
  currentLocale.value = locale
  localStorage.setItem('app-locale', locale)
  console.log('Vue LocaleProvider: 语言已切换为', locale)
}

// 初始化语言设置
const initializeLocale = () => {
  // 从 localStorage 读取保存的语言环境
  const savedLocale = localStorage.getItem('app-locale') as SupportedLocale
  const validLocales: SupportedLocale[] = ['zh-CN', 'en-US']

  // 如果有保存的语言设置，使用保存的设置
  if (savedLocale && validLocales.includes(savedLocale)) {
    currentLocale.value = savedLocale
    console.log('Vue LocaleProvider: 使用保存的语言设置', savedLocale)
  } else {
    // 否则自动检测浏览器语言
    const detectedLocale = detectBrowserLocale()
    currentLocale.value = detectedLocale
    console.log('Vue LocaleProvider: 自动检测到语言', detectedLocale)
  }
}

// 提供语言上下文
provide('locale', {
  currentLocale,
  setLocale
})

// 组件挂载时初始化
onMounted(() => {
  initializeLocale()
})
</script>
